services:
  chirpstack:
    image: chirpstack/chirpstack:4
    command: -c /etc/chirpstack
    restart: unless-stopped
    networks:
      - lora
    ports:
      - 8080:8080
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
      - ./lorawan-devices-repo:/tmp/lorawan-devices
    depends_on:
      - postgres
      - mosquitto
      - redis
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - REDIS_HOST=redis
      - POSTGRESQL_HOST=postgres
      - CHIRPSTACK_SECRET=$CHIRPSTACK_SECRET

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    networks:
      - lora
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    environment:
      - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=au915_1/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=au915_1/gateway/{{ .GatewayID }}/state/{{ .StateType }}
      - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=au915_1/gateway/{{ .GatewayID }}/command/#
    depends_on:
      - mosquitto

  chirpstack-gateway-bridge-basicstation:
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-au915_1.toml
    networks:
      - lora
    ports:
      - 3001:3001
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on:
      - mosquitto

  chirpstack-rest-api:
    image: chirpstack/chirpstack-rest-api:4
    restart: unless-stopped
    command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
    networks:
      - lora
    ports:
      - 8090:8090
    depends_on:
      - chirpstack

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    networks:
      - lora
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
    depends_on:
      - kea
      - bind

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save 300 1 --save 60 100 --appendonly no
    networks:
      - lora
    volumes:
      - redisdata:/data
    depends_on:
      - kea
      - bind

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    networks:
      - lora
    ports:
      - 1883:1883
    volumes:
      - ./configuration/mosquitto/config/:/mosquitto/config/
    depends_on:
      - kea
      - bind

  lora-proxy:
    build: ./lora-proxy
    restart: unless-stopped
    command: npm run dev
    networks:
      - lora
    ports:
      - 3000:3000
    volumes:
      - ./lora-proxy/:/etc/nginx/conf.d/
      - proxydata:/data/
    depends_on:
      - kea
      - bind
      - chirpstack
    environment:
      # - MQTT_BROKER_HOST=broker.emqx.io

      # - MQTT_BROKER_HOST=au1.cloud.thethings.network
      # - MQTT_BROKER_TYPE=ttn
      # - MQTT_APP_ID=$TTN_USERNAME

      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_TYPE=chirpstack
      - MQTT_APP_ID=$CHIRPSTACK_APPLICATION_ID

      - WEBHOOK_TARGET=http://game.darends.scouthack.com:3333/api/injest
    develop:
      watch:
        - action: sync
          path: ./lora-proxy
          target: ./home/node/app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./lora-proxy/package.json

  nginx:
    image: nginx:latest
    restart: unless-stopped
    networks:
      - lora
    ports:
      - 8001:80
    volumes:
      - ./configuration/nginx/:/etc/nginx/conf.d/
      - ./nginx/default/:/usr/share/nginx/html:ro
    depends_on:
      - kea
      - bind
      - lora-proxy
      - chirpstack

  kea:
    # https://gitlab.isc.org/isc-projects/kea-docker
    image: docker.cloudsmith.io/isc/docker/kea-dhcp4:2.5.2
    restart: unless-stopped
    networks:
      - kea
    ports:
      - 192.168.50.1:67:67/tcp
      - 192.168.50.1:67:67/udp
    volumes:
      - ./configuration/isc-kea/kea-dhcp4.conf:/etc/kea/kea-dhcp4.conf

  bind:
    # https://hub.docker.com/r/internetsystemsconsortium/bind9
    image: internetsystemsconsortium/bind9:9.18
    restart: unless-stopped
    networks:
      - lora
    # ports:
    #   - 53:53/udp
    #   - 53:53/tcp
    volumes:
      - ./configuration/bind/:/etc/bind

volumes:
  postgresqldata:
  redisdata:
  proxydata:

networks:
  kea:
    driver: ipvlan
    # driver_opts:
    #   parent: br0
    ipam:
      driver: default
      config:
        - subnet: "192.168.50.0/24"
  lora:
    driver: bridge
