network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      dhcp4: true
      dhcp4-overrides:
        use-dns: false
    enp2s0:
      dhcp4: false
    enp3s0:
      dhcp4: false
    enp4s0:
      dhcp4: false
  bridges:
    br0:
      addresses:
        - 192.168.50.1/24
      nameservers:
        search: [darends.scouthack.com]
        addresses: [192.168.50.1, 8.8.8.8]
      interfaces:
        - enp2s0
        - enp3s0
        - enp4s0
